# Generated by Django 5.0.4 on 2024-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Director", "0007_alter_directorimage_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
