# Generated by Django 5.0.4 on 2024-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Actor", "0004_alter_actorimage_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
