# Generated by Django 5.0.4 on 2024-07-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rate", "0003_rate_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
