# Generated by Django 5.0.4 on 2024-07-14 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0014_alter_movievideo_title"),
        ("Rate", "0005_alter_rate_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_rate",
                to="Movie.movie",
            ),
        ),
    ]
