# Generated by Django 5.0.4 on 2024-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0009_alter_movie_actor_actor_alter_movievideo_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="revenue",
            field=models.BigIntegerField(default=0),
        ),
    ]
