# Generated by Django 5.0.4 on 2024-07-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0011_alter_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
