# Generated by Django 5.0.4 on 2024-07-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0012_alter_movie_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movievideo",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
