# Generated by Django 5.0.4 on 2024-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0014_alter_movievideo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie_actor",
            name="character_name",
            field=models.CharField(max_length=100),
        ),
    ]
