# Generated by Django 5.0.4 on 2024-07-11 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Review", "0008_remove_review_num_vote_down_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("account", "review")},
        ),
    ]
